app/urls.py
from django.urls import path
from .views import *

app_name='app'

urlpatterns = [
  path('yfcases/', YfcaseList.as_view(), name='list_yfcases'),
  path('create/', YfcaseCreate.as_view(), name='create_yfcase'),
  path('update/<int:pk>/', YfcaseUpdate.as_view(), name='update_yfcase'),
  path('delete/<int:pk>/', YfcaseDelete.as_view(), name='delete_yfcase'),
  path('delete-land/<int:pk>/', delete_land, name='delete_land'),
  path('delete-build/<int:pk>/', delete_build, name='delete_build'),
  path('delete-person/<int:pk>/', delete_person, name='delete_person'),
]

src/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
  path('admin/', admin.site.urls),
  path('', include('app.urls')),
]

templates/app/item_confirm_delete.html
<!-- item_confirm_delete.html -->
{% extends 'base.html' %}

{% block content %}
  <h2>Delete Item</h2>
  <p>Are you sure you want to delete "{{ object }}"?</p>
  <form method="post" action="{% url 'item_delete' pk=object.pk %}">
    {% csrf_token %}
    <button type="submit">Confirm Delete</button>
  </form>
  <a href="{% url 'item_list' %}">Cancel</a>
{% endblock %}

templates/app/item_detail.html
<!-- item_detail.html -->
{% extends 'base.html' %}

{% block content %}
  <h2>Item Details</h2>
  <p><strong>Name:</strong> {{ item.name }}</p>
  <p><strong>Description:</strong> {{ item.description }}</p>
  <a href="{% url 'item_list' %}">Back to Item List</a>
  {% include 'app/partials/baseData.html' %}
  {% include 'app/partials/land.html' %}
  {% include 'app/partials/build.html' %}
  {% include 'app/partials/person.html' %}

{% endblock %}

templates/app/item_form.html
<!-- item_form.html -->
{% extends 'base.html' %}

{% block content %}
  <h2>{% if object %}Update{% else %}Create{% endif %} Item</h2>
  <form method="post" action="{% if object %}{% url 'item_update' pk=object.pk %}{% else %}{% url 'item_create' %}{% endif %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">{% if object %}Update{% else %}Create{% endif %} Item</button>
  </form>
  <a href="{% url 'item_list' %}">Back to Item List</a>
{% endblock %}

templates/app/item_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
  <table class="table text-center align-middle">
    <thead>
      <tr>
        <th scope="col" class="align-middle">序號</th>
        <th scope="col" class="align-middle">案號</th>
        <th scope="col" class="align-middle">兩週內<br>應買止日</th>
        <th scope="col" class="align-middle">負責人</th>
        <th scope="col" class="align-middle">最終判定</th>
        <th scope="col" class="align-middle">執行結果</th>
        <th scope="col" class="align-middle">優購結果</th>
        <th scope="col" class="align-middle">標的編號</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">0473</th>
        <td>112年度司執字第031506號 (孔股)<br>➥新竹縣湖口鄉松江二街16號5(5層)</td>
        <td>11天後</td>
        <td>賈桂琳	</td>
        <td>3拍進場</td>
        <td>第三人搶標	</td>
        <td>遭優購</td>
        <td>YF001</td>
      </tr>
    </tbody>
  </table> 
</div>


<h2>Item List</h2>
  <ul>
    {% for item in object_list %}
    <a href="{% url 'item_detail' item.id %}">
      <li>{{ item.name }} - {{ item.description }}-{{item.id}}</li>
    </a>
    <a href="{% url 'item_update' item.id %}">
      update
    </a>
    <a href="{% url 'item_delete' item.id %}">
      Delete
    </a>
    {% endfor %}
  </ul>
  <a href="{% url 'item_create' %}">Create New Item</a>
{% endblock content %}

templates/app/yfcase_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Confirm deletion</h1>
  <p>Are you sure you want to delete the product "{{ object }}"?</p>

  <form method="post">
    {% csrf_token %}
    <button type="submit">Confirm Delete</button>
  </form>

  <a href="{% url 'app:list_yfcases' %}">Cancel</a>
{% endblock %}

templates/app/yfcase_create_or_update.html
{% extends "base.html" %}


{% block content %}
<form enctype="multipart/form-data" class="container" method="post" id="product_form">
  {% csrf_token %}
  <!-- main form start --- in our case product form -->
  <div class="card">
    <div class="card-header card-header-secondary">
      <h4 class="card-title">Add Products</h4>
    </div>
    {% for field in form %}
      <div class="form-group card-body">
        <label>{{field.label}}</label>
        {% if field.field.required %}
          <span style="color: red;" class="required">*</span>
        {% endif %}
    
        {{field}}


        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </div>
    {% endfor %}
  </div>
   
  {% with named_formsets.lands as formset %}  
    {{ formset.management_form }}
    <script type="text/html" id="lands-template">  
      <tr id="lands-__prefix__" class= hide_all> 
        {% for fields in formset.empty_form.hidden_fields %}
          {{ fields }}
        {% endfor %}
    
        {% for fields in formset.empty_form.visible_fields %}
          <td>{{fields}}</td>
        {% endfor %}
      </tr>
    </script>
    <div class="table-responsive card mt-4">
      <div class="card-header card-header-secondary">
        <h4 class="card-title">新增地號</h4>
      </div>
      <table class="table card-body">
        <thead class="text-secondary">
          <th>地號 <span style="color: red;" class="required">*</span></th>
          <th>謄本</th>
          <th>地坪(平方公尺)</th>
          <th>個人持分</th>
          <th>所有持分</th>
          <th>備註</th>
          <th>刪除?</th>
          <th>自訂刪除</th>
        </thead>
        <tbody id="item-lands">
          {% for error in formset.non_form_errors %}
            <span style="color: red">{{ error }}</span>
          {% endfor %}
          {% for formss in formset %}
            {{ formss.management_form }}
            <tr id="lands-{{ forloop.counter0 }}" class= hide_all>  <!-- id="inlineformsetname-counter" -->
              {{ formss.id }}
              {% for field in formss.visible_fields %}
                <td>
                  {{field}}
                  {% for error in field.errors %}
                    <span style="color: red">{{ error }}</span>
                  {% endfor %}
                </td>
              {% endfor %}
                <!-- delete code -->
              {% if formss.instance.pk %}
                <td>
                  <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal{{formss.instance.pk}}">
                      Delete
                  </button>
                  <!-- Modal -->
                  <div class="modal fade" id="exampleModal{{formss.instance.pk}}" tabindex="-1" aria-labelledby="exampleModalLabel{{formss.instance.pk}}" aria-hidden="true">
                      <div class="modal-dialog" role="document">
                          <div class="modal-content">
                              <div class="modal-header">
                                  <h5 class="modal-title" id="exampleModalLabel{{formss.instance.pk}}">
                                      Are You Sure You Want To Delete This?
                                  </h5>
                                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                              </div>
                              <div class="modal-footer">
                                  <a href="{% url 'app:delete_land' formss.instance.pk %}" type="button" class="btn btn-primary">
                                      Yes, Delete
                                  </a>
                                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                              </div>
                          </div>
                      </div>
                  </div>
                </td>
              {% endif %}
            </tr>
          {% endfor %}
        </tbody>
      </table>
      <a href="#" id="add-land-button" class="btn btn-secondary add-lands">Add More</a> <!-- id="add-inlineformsetname-button" -->
    </div>
  {% endwith %}


  {% with named_formsets.builds as formset %}
    {{ formset.management_form }}
    <script type="text/html" id="builds-template">  
      <tr id="builds-__prefix__" class= hide_all>
        {% for fields in formset.empty_form.hidden_fields %}
          {{ fields }}
        {% endfor %}
    
        {% for fields in formset.empty_form.visible_fields %}
          <td>{{fields}}</td>
        {% endfor %}
      </tr>
    </script>
    <div class="table-responsive card mt-4">
      <div class="card-header card-header-secondary">
        <h4 class="card-title">新增建號</h4>
      </div>
      <table class="table card-header">
        <thead class="text-secondary">
          <th>建號 <span style="color: red;" class="required">*</span></th>
          <th>謄本</th>
          <th>建坪(平方公尺)</th>
          <th>個人持分</th>
          <th>所有持分</th>
          <th>建物型</th>
          <th>使用分區</th>
          <th>備註</th>
          <th>附屬建物用途</th>
          <th>附屬建物面積</th>
          <th>刪除?</th>
          <th>自訂刪除</th>
        </thead>
        <tbody id="item-builds">  
          {% for error in formset.non_form_errors %}
            <span style="color: red">{{ error }}</span>
          {% endfor %}
          {% for formss in formset %}
            {{ formss.management_form }}
            <tr id="builds-{{ forloop.counter0 }}" class= hide_all>  <!-- id="inlineformsetname-counter" -->
              {{ formss.id }}
              {% for field in formss.visible_fields %}
                <td>
                  {{field}}
                  {% for error in field.errors %}
                    <span style="color: red">{{ error }}</span>
                  {% endfor %}
                  
                  {% comment %} {{ field.DELETE }} {% endcomment %}
                </td>
              {% endfor %}


              {% comment %} for delete {% endcomment %}
              
              {% if formss.instance.pk %}
                <td>
                  <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal{{formss.instance.pk}}">
                      Delete
                  </button>
                  <!-- Modal -->
                  <div class="modal fade" id="exampleModal{{formss.instance.pk}}" tabindex="-1" aria-labelledby="exampleModalLabel{{formss.instance.pk}}" aria-hidden="true">
                      <div class="modal-dialog" role="document">
                          <div class="modal-content">
                              <div class="modal-header">
                                  <h5 class="modal-title" id="exampleModalLabel{{formss.instance.pk}}">
                                      Are You Sure You Want To Delete This?
                                  </h5>
                                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                              </div>
                              <div class="modal-footer">
                                  <a href="{% url 'app:delete_build' formss.instance.pk %}" type="button" class="btn btn-primary">Yes, Delete</a>
                                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                              </div>
                          </div>
                      </div>
                  </div>
                </td>
              {% endif %}
            </tr>
          {% endfor %}
        </tbody>
      </table>
      <a href="#" id="add-build-button" class="btn btn-secondary add-builds">Add More</a> <!-- id="add-inlineformsetname-button" -->
    </div>
      
  {% endwith %}

  {% with named_formsets.people as formset %}
    {{ formset.management_form }}
    <script type="text/html" id="people-template">  
      <tr id="people-__prefix__" class= hide_all>
        {% for fields in formset.empty_form.hidden_fields %}
          {{ fields }}
        {% endfor %}
    
        {% for fields in formset.empty_form.visible_fields %}
          <td>{{fields}}</td>
        {% endfor %}
      </tr>
    </script>
    <div class="table-responsive card mt-4">
      <div class="card-header card-header-secondary">
        <h4 class="card-title">新增人員</h4>
      </div>
      <table class="table card-header">
        <thead class="text-secondary">
          <th>姓名 <span style="color: red;" class="required">*</span></th>
          <th>共有人</th>
          <th>Delete?</th>
          <th>Custom Delete btn</th>
        </thead>
        <tbody id="item-people">  
          {% for error in formset.non_form_errors %}
            <span style="color: red">{{ error }}</span>
          {% endfor %}
          {% for formss in formset %}
            {{ formss.management_form }}
            <tr id="people-{{ forloop.counter0 }}" class= hide_all>  <!-- id="inlineformsetname-counter" -->
              {{ formss.id }}
              {% for field in formss.visible_fields %}
                <td>
                  {{field}}
                  {% for error in field.errors %}
                    <span style="color: red">{{ error }}</span>
                  {% endfor %}
                  
                  {% comment %} {{ field.DELETE }} {% endcomment %}
                </td>
              {% endfor %}


              {% comment %} for delete {% endcomment %}
              
              {% if formss.instance.pk %}
                <td>
                  <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal{{formss.instance.pk}}">
                    Delete
                </button>
                
                  <!-- Modal -->
                  <div class="modal fade" id="exampleModal{{formss.instance.pk}}" tabindex="-1" aria-labelledby="exampleModalLabel{{formss.instance.pk}}" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel{{formss.instance.pk}}">
                                    Are You Sure You Want To Delete This?
                                </h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-footer">
                                <a href="{% url 'app:delete_person' formss.instance.pk %}" type="button" class="btn btn-primary">Yes, Delete</a>
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </div>                
                </td>
              {% endif %}
            </tr>
          {% endfor %}
        </tbody>
      </table>
      <a href="#" id="add-person-button" class="btn btn-secondary add-people">Add More</a> <!-- id="add-inlineformsetname-button" -->
    </div>
      
  {% endwith %}


  <div class="form-group">
    <button type="submit" class="btn btn-secondary btn-block">Submit</button>
  </div>
</form>


<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>


<script>
  $(document).ready(function() {
    $('.add-lands').click(function(ev) {
      ev.preventDefault();
      var count = $('#item-lands').children().length;
      var tmplMarkup = $('#lands-template').html();
      var compiledTmpl = tmplMarkup.replace(/__prefix__/g, count);
      $('#item-lands').append(compiledTmpl);
      $('#id_lands-TOTAL_FORMS').attr('value', count+1);
    });
  });


  $(document).ready(function() {
    $('.add-builds').click(function(ev) {
      ev.preventDefault();
      var count = $('#item-builds').children().length;
      var tmplMarkup = $('#builds-template').html();
      var compiledTmpl = tmplMarkup.replace(/__prefix__/g, count);
      $('#item-builds').append(compiledTmpl);
      $('#id_builds-TOTAL_FORMS').attr('value', count+1);
    });
  });

  $(document).ready(function() {
    $('.add-people').click(function(ev) {
      ev.preventDefault();
      var count = $('#item-people').children().length;
      var tmplMarkup = $('#people-template').html();
      var compiledTmpl = tmplMarkup.replace(/__prefix__/g, count);
      $('#item-people').append(compiledTmpl);
      $('#id_people-TOTAL_FORMS').attr('value', count+1);
    });
  });
</script>
        
{% endblock content %}

templates/app/yfcase_list.html
{% extends "base.html" %}
{% block content %}
  <div class="card">
    <div class="card-header card-header-secondary">
      <h4 class="card-title">Yfcases</h4>
      <a href="{% url 'app:create_yfcase' %}">
        Add more yfcases
      </a>
    </div>
    <ul>
      {% for yfcase in yfcases %}
        <li class="card-body">{{ yfcase.yfcaseCaseNumber }} | 
          <a href="{% url 'app:update_yfcase' yfcase.id %}">
            Edit
          </a>
          | 
          <a href="{% url 'app:delete_yfcase' yfcase.id %}">
            Delete
          </a>
        </li>
      {% endfor %}
    </ul>
  </div>
{% endblock content %}